version: "3"

# This file doesn't run alone.
# Use the "compose.sh" script

services:

  server:
    container_name: unbabel_dev_server
    command: python -m flask run --host=0.0.0.0
    environment:
      - DEBUG=True
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend_app:/app
