version: "3"

services:

  redis:
    container_name: unbabel_redis
    image: redis:3.2.11

  db:
    container_name: unbabel_db
    image: postgres:10.3
    environment:
      - POSTGRES_DB=unbabel_dev_db
      - POSTGRES_USER=unbabel_dev_user
      - POSTGRES_PASSWORD=unbabel_dev_pass

  server:
    container_name: unbabel_dev_server
    build:
      context: ./backend_app
      dockerfile: Dockerfile.dev
    command: python -m flask run --host=0.0.0.0
    environment:
      - DEBUG=True
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis/0
      - DATABASE_URL=postgres://unbabel_dev_user:unbabel_dev_pass@db/unbabel_dev_db
    volumes:
      - ./backend_app:/app
    ports:
      - "5000:5000"
    links:
      - db
      - redis
