version: "3"

services:

  db:
    container_name: unbabel_db
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=unbabel_pass
      - POSTGRES_USER=unbabel_user
      - POSTGRES_DB=unbabel_db

  server:
    container_name: unbabel_server
    build: ./backend_app
    command: gunicorn -b 0.0.0.0:5000 wsgi --log-file -
    environment:
      - DATABASE_URL=postgres://unbabel_user:unbabel_pass@db/unbabel_db
    ports:
      - "5000:5000"
    links:
      - db
