version: "3"

services:

  redis:
    container_name: unbabel_redis
    image: redis:3.2.11

  db:
    container_name: unbabel_db
    image: postgres:10.3
    environment:
      - POSTGRES_DB=unbabel_db
      - POSTGRES_USER=unbabel_user
      - POSTGRES_PASSWORD=unbabel_pass

  server:
    container_name: unbabel_server
    build: ./backend_app
    command: bash -c 'flask db upgrade && gunicorn -b 0.0.0.0:5000 wsgi --log-file -'
    environment:
      - REDIS_URL=redis://redis/0
      - DATABASE_URL=postgres://unbabel_user:unbabel_pass@db/unbabel_db
    ports:
      - "5000:5000"
    links:
      - db
      - redis

  frontend:
    container_name: unbabel_frontend
    build: ./frontend_app
    command: node .
    environment:
      - API_URL=http://localhost:5000/api/
    ports:
      - "3000:3000"
    depends_on:
      - server

